export const CATEGORIES = [
  {
    slug: 'flooring',
    longDesc: "නව නිවසක ටයිල් ඇල්ලීම, පැරණි බිම් වෙනස් කිරීම හෝ ගරාජයක ඉපොක්සි යෙදීම වේවා, බිම් නිමාව නිවසට විශාල වෙනසක් කරයි. වැඩHUB දිස්ත්‍රික්ක 25 පුරා සත්‍යාපිත බිම් ටයිල්, පාකේ, ලැමිනේට් සහ ඉපොක්සි කාර්මිකයන් ලැයිස්තුගත කරයි. පළපුරුද්ද සහ සමාලෝචන සසඳා WhatsApp හරහා සෘජුව අමතන්න. ටයිල් ප්‍රමාණය අනුව ශ්‍රම ගාස්තු වර්ග අඩියකට රු. 100–250 පමණයි.",
    label: "බිම් සේවා",
    icon: '⬜',
    color: '#8A6224',
    bg: '#F5EEE2',
    border: '#E8DCC6',
    count: 10,
    desc: "ශ්‍රී ලංකාව පුරා සත්‍යාපිත බිම් විශේෂඥයන් සොයන්න — ටයිල්, ඉපොක්සි, පාකේ, වයිනයිල් සහ තවත් දේ.",
    terms: ['floor', 'tiling', 'tile', 'mosaic', 'epoxy', 'parquet', 'laminate', 'vinyl', 'granite', 'staircase'],
    blogSlugs: ['large-format-tiles-guide', 'best-tiles-for-bathroom-floor'],
  },
  {
    slug: 'bathroom',
    longDesc: "නාන කාමරයක් නිවසේ වැඩිම තාක්ෂණික සැලකිල්ල අවශ්‍ය කාමරයයි. දුර්වල ජලරෝධනය වසර 2–3කින් අලුත්වැඩියාව අසාර්ථක වීමේ ප්‍රධාන හේතුවයි. නිසි පටල සහ ස්ක්‍රීඩ් ක්‍රම අනුගමනය කරන සත්‍යාපිත නාන කාමර, ජලනළ සහ ජලරෝධන විශේෂඥයන් වැඩHUB හරහා සම්බන්ධ කරගන්න. තීරණයට පෙර ව්‍යාපෘතිය නොමිලේ පළ කර අයිතම අනුව මිල ගණන් සසඳන්න.",
    label: "නාන කාමර සේවා",
    icon: '🚿',
    color: '#2F6B4F',
    bg: '#E9F1EC',
    border: '#A9CBB8',
    count: 7,
    desc: "සත්‍යාපිත විශේෂඥයන්ගෙන් නාන කාමර අලුත්වැඩියා, ජලනළ, ජලරෝධන සහ උපාංග සේවා.",
    terms: ['bathroom', 'bath', 'shower', 'vanity', 'plumbing', 'waterproof', 'mirror'],
    blogSlugs: ['bathroom-renovation-cost-sri-lanka', 'waterproofing-bathroom-guide'],
  },
  {
    slug: 'kitchen',
    longDesc: "මුළුතැන්ගෙයි අලුත්වැඩියාවක ටයිල්, කබඩ සහ බිත්ති ආවරණ නිවැරදි අනුපිළිවෙළට කළ යුතුයි. මෙහි කොන්ත්‍රාත්කරුවන් ශ්‍රී ලංකාව පුරා පැන්ට්‍රි කබඩ, ග්‍රැනයිට් වැඩතල සහ බිත්ති ටයිල් වැඩ කරයි. ආරම්භයට පෙර වැඩHUB හරහා WhatsApp මිල ගණන් කිහිපයක් නොමිලේ ගන්න.",
    label: "මුළුතැන්ගෙයි සේවා",
    icon: '🍳',
    color: '#8A6224',
    bg: '#F5EEE2',
    border: '#F0EADF',
    count: 2,
    desc: "පළපුරුදු කොන්ත්‍රාත්කරුවන්ගෙන් මුළුතැන්ගෙයි අලුත්වැඩියා, කබඩ සහ ටයිල් වැඩ.",
    terms: ['kitchen', 'cabinet', 'splashback'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'glass',
    longDesc: "වීදුරු අත්වැට, ඇලුමිනියම් දොර ජනෙල්, ජිප්සම් සහ අයිපැනල් සිවිලිම්වල කල්පැවැත්ම සවිකිරීමේ නිරවද්‍යතාව මත රඳාපවතී. වැඩHUB ශ්‍රී ලංකාව පුරා සත්‍යාපිත වීදුරු සහ ඇලුමිනියම් කාර්මිකයන් පෙර වැඩ ඡායාරූප සමඟ පෙන්වයි. සසඳා WhatsApp හරහා අමතන්න.",
    label: "වීදුරු සහ ඇලුමිනියම්",
    icon: '🪟',
    color: '#6B4A18',
    bg: '#F5EEE2',
    border: '#E8DCC6',
    count: 6,
    desc: "වීදුරු අත්වැට, ඇලුමිනියම් දොර ජනෙල්, අයිපැනල් සිවිලිම් සහ ජිප්සම් වැඩ.",
    terms: ['glass', 'aluminium', 'aluminum', 'railing', 'ceiling', 'ipanel', 'gypsum', 'gate', 'fencing', 'door', 'window'],
    blogSlugs: ['how-to-choose-a-tiler', 'best-tiles-for-bathroom-floor'],
  },
  {
    slug: 'construction',
    longDesc: "වහල සහ බදාම සිට කාමර බිත්ති සහ සම්පූර්ණ ඉදිකිරීම් දක්වා ශ්‍රී ලංකාව පුරා ව්‍යුහාත්මක සහ නිමාව වැඩ කරන සත්‍යාපිත කොන්ත්‍රාත්කරුවන්. වැඩHUB හි නොමිලේ පළ කර කොමිස් නැති තරගකාරී මිල ගණන් ලබාගන්න.",
    label: "ඉදිකිරීම් සේවා",
    icon: '🏗️',
    color: '#4A4A4A',
    bg: '#F7F7F7',
    border: '#E2E2E2',
    count: 9,
    desc: "වහල, බදාම, වෙන්කිරීමේ බිත්ති, කොන්ක්‍රීට් සහ සම්පූර්ණ ඉදිකිරීම් සේවා.",
    terms: ['roof', 'plaster', 'partition', 'water tank', 'concrete', 'masonry', 'carpentry', 'debris', 'demolition', 'cleaning', 'construction'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'outdoor',
    longDesc: "ගෙවතු, තටාක, පේවිං සහ පර්ගෝලා වැඩ සඳහා ශ්‍රී ලංකාවේ මෝසම් ජල බැසයාම සහ හිරු නිරාවරණය තේරුම්ගන්නා කොන්ත්‍රාත්කරුවන් අවශ්‍යයි. මෙහි විශේෂඥයන්ට සත්‍යාපිත පැතිකඩ සහ පෙර වැඩ ඡායාරූප ඇත. වැඩHUB හි නොමිලේ මිල ගණන් සසඳන්න.",
    label: "එළිමහන් සේවා",
    icon: '🌿',
    color: '#285C43',
    bg: '#E9F1EC',
    border: '#C6DDCF',
    count: 4,
    desc: "ගෙවතු අලංකරණය, තටාක ඉදිකිරීම්, පේවිං, වාහන පිවිසුම් සහ පර්ගෝලා ව්‍යුහ.",
    terms: ['outdoor', 'landscape', 'garden', 'pool', 'paving', 'driveway', 'pergola', 'shade'],
    blogSlugs: ['large-format-tiles-guide', 'post-tiling-project-tilershub'],
  },
  {
    slug: 'trades',
    longDesc: "නිවාස පින්තාරු, විදුලි රැහැන්, වායු සමීකරණ, සූර්ය සහ ස්මාර්ට් නිවාස සවිකිරීම් අලුත්වැඩියාව සම්පූර්ණ කරයි. වැඩHUB හි සෑම කාර්මිකයෙකුම පළ කිරීමට පෙර සමාලෝචනය කරයි. නොමිලේ පළ කර WhatsApp මිල ගණන්වලින් තෝරන්න.",
    label: "වෘත්තීය සහ වෙනත් සේවා",
    icon: '🎨',
    color: '#8A6224',
    bg: '#F5EEE2',
    border: '#F0EADF',
    count: 9,
    desc: "නිවාස පින්තාරු, විදුලි, වායු සමීකරණ, සූර්ය පැනල, CCTV සහ ස්මාර්ට් නිවාස සවිකිරීම්.",
    terms: ['paint', 'lighting', 'wiring', 'electrical', 'air condition', 'solar', 'cctv', 'security', 'smart home', 'automation'],
    blogSlugs: ['how-to-choose-a-tiler', 'post-tiling-project-tilershub'],
  },
]
