import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync,readdirSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',admin='33333333-3333-4333-8333-333333333333',provider='44444444-4444-4444-8444-444444444444';
test('growth flow protects registrations, new job photos, certificate privacy and service search',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);insert into auth.users values('${owner}'),('${other}'),('${admin}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create function public.is_admin() returns boolean language sql stable as $$select coalesce(auth.uid()='${admin}',false)$$;
 grant usage on schema auth,storage to anon,authenticated;
 create table providers(id uuid primary key,user_id uuid,name text,slug text,provider_type text,city text,district text,services text[],profile_image text,verification_status text,service_areas text[],status text,merged_into uuid,description text);
 insert into providers(id,user_id,name,slug,provider_type,status) values('${provider}','${owner}','Example','example','plumber','active');
 alter table providers enable row level security;grant select on providers to anon,authenticated;
 create policy visible on providers for select using(status='active' or user_id=auth.uid());
 create table reviews(provider_id uuid,rating int,status text,confirmed_job boolean,engagement_id uuid);grant select on reviews to anon,authenticated;
 create table job_engagements(id uuid primary key,provider_id uuid references providers(id),data jsonb);
 create table provider_submissions(id uuid primary key default gen_random_uuid(),user_id uuid,status text,city text not null);
 grant select,insert on provider_submissions to authenticated;
 alter table provider_submissions enable row level security;create policy owner on provider_submissions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
 create table projects(id uuid primary key default gen_random_uuid(),user_id uuid,images text[],status text);
 insert into projects(user_id,status) values('${owner}','active');grant select,insert,update on projects to authenticated;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,created_at timestamptz default now());
 alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to anon,authenticated;`);
 const migration=async suffix=>{const file=readdirSync('supabase/migrations').find(f=>f.endsWith(suffix));await db.exec(readFileSync('supabase/migrations/'+file,'utf8'));};
 for(const suffix of ['_hierarchical_provider_skills.sql','_provider_discovery_evidence.sql','_private_provider_credentials.sql','_credential_upload_limits_and_audit.sql','_provider_service_offerings.sql','_provider_growth_safeguards.sql','_activate_job_photo_requirement.sql'])await migration(suffix);
 const as=async(role,id='')=>db.exec(`reset role;set role ${role};set test.uid='${id}';`);
 await as('authenticated',owner);
 await assert.rejects(db.exec(`insert into provider_submissions(user_id,status) values('${owner}','pending_review')`),/already exists/);
 await as('authenticated',other);
 await db.exec(`insert into provider_submissions(user_id,status) values('${other}','pending_review')`);
 await assert.rejects(db.exec(`insert into provider_submissions(user_id,status) values('${other}','pending_review')`),/unique/);
 await as('authenticated',owner);
 await db.exec("update projects set status='closed'"); // historical jobs remain editable
 await assert.rejects(db.exec(`insert into projects(user_id,status) values('${owner}','active')`),/1 and 5/);
 const path=`${owner}/55555555-5555-4555-8555-555555555555.jpg`;
 const url=`https://ginrgwaciblcvxvkbeyd.supabase.co/storage/v1/object/public/job-images/${path}`;
 await assert.rejects(db.exec(`insert into projects(user_id,images) values('${owner}',array['${url}'])`),/ownership or upload/);
 await db.exec(`insert into storage.objects(bucket_id,name) values('job-images','${path}');insert into projects(user_id,images) values('${owner}',array['${url}'])`);
 await assert.rejects(db.exec(`insert into projects(user_id,images) values('${other}',array['${url}'])`),/ownership or upload/);
 await assert.rejects(db.exec(`insert into projects(user_id,images) values('${owner}',array['${url}','${url}'])`),/Duplicate/);
 await assert.rejects(db.exec("update projects set images='{}' where images is not null"),/1 and 5/);
 await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('job-images','${other}/55555555-5555-4555-8555-555555555555.jpg')`),/ownership/);
 await db.exec(`insert into storage.objects(bucket_id,name) select 'job-images','${owner}/'||gen_random_uuid()||'.jpg' from generate_series(1,24)`);
 await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('job-images','${owner}/'||gen_random_uuid()||'.jpg')`),/Daily/);
 const cred='55555555-5555-4555-8555-555555555555';
 await db.exec(`insert into provider_credentials(id,provider_id,user_id,credential_type,qualification_name,issuing_organization,public_listing) values('${cred}','${provider}','${owner}','credential','NVQ Level 4 Plumbing','Training Institute',true)`);
 assert.equal((await db.query('select * from provider_qualification_summaries')).rows.length,0);
 await assert.rejects(db.exec(`update provider_credentials set status='pending' where id='${cred}'`),/supporting document/);
 const doc=(await db.query(`select reserve_credential_upload('${cred}','application/pdf') as path`)).rows[0].path;
 await db.exec(`insert into storage.objects(bucket_id,name) values('credential-documents','${doc}');update provider_credentials set document_path='${doc}',status='pending' where id='${cred}'`);
 await db.exec(`insert into provider_service_offerings(provider_id,title,description,pricing_model,amount,unit_label) values('${provider}','Large format tiling','Bathroom renovation','per_sqft',200,null)`);
 await assert.rejects(db.exec(`insert into provider_service_offerings(provider_id,title,pricing_model,amount) values('${provider}','Invalid price','fixed','NaN')`),/finite_prices/);
 await as('anon');
 const summary=(await db.query('select * from provider_qualification_summaries')).rows[0];assert.equal(summary.status,'pending');assert.equal('document_path' in summary,false);assert.equal('certificate_number' in summary,false);
 await assert.rejects(db.exec('select * from provider_credentials'),/permission denied/);
 assert.equal((await db.query("select * from storage.objects where bucket_id='credential-documents'")).rows.length,0);
 assert.equal((await db.query("select * from discover_service_providers('renovation large')")).rows.length,1);
 assert.equal((await db.query("select * from discover_service_providers('renovation unavailable')")).rows.length,0);
 await assert.rejects(db.exec("update provider_qualification_summaries set status='verified'"),/permission denied/);
 await as('authenticated',admin);
 await db.exec(`update provider_credentials set status='rejected',verification_method='manual',review_note='Document could not be confirmed' where id='${cred}'`);
 await as('anon');assert.equal((await db.query('select * from provider_qualification_summaries')).rows.length,0);
 }finally{await db.close();}
});
